"use strict";
// Generated by tools/build_maps.py -- do not edit by hand.
// Per-(level, area) top-down map backgrounds for the Map tab, keyed by
// level folder then area number. Each entry is the world-space rectangle
// (x/z plane) its image covers: left=x1, right=x2, top=z1, bottom=z2
// (north up, +z downward). Images derived from STROOP (MIT, (c) 2019
// SM64 TAS & ABC) -- see maps/STROOP-LICENSE.txt.
window.SM64_MAPS = {
  "bbh": { "1": { img: "maps/bbh_1.webp", x1: -4197, x2: 5530, z1: -3993, z2: 6758 } },
  "bitdw": { "1": { img: "maps/bitdw_1.webp", x1: -8191, x2: 8192, z1: -8191, z2: 8192 } },
  "bitfs": { "1": { img: "maps/bitfs_1.webp", x1: -8191, x2: 8192, z1: -8191, z2: 8192 } },
  "bits": { "1": { img: "maps/bits_1.webp", x1: -8191, x2: 8192, z1: -8191, z2: 8192 } },
  "bob": { "1": { img: "maps/bob_1.webp", x1: -8191, x2: 8192, z1: -8191, z2: 8192 } },
  "bowser_1": { "1": { img: "maps/bowser_1_1.webp", x1: -7167, x2: 7168, z1: -7167, z2: 7168 } },
  "bowser_2": { "1": { img: "maps/bowser_2_1.webp", x1: -6545, x2: 6546, z1: -6545, z2: 6546 } },
  "bowser_3": { "1": { img: "maps/bowser_3_1.webp", x1: -8191, x2: 8192, z1: -8191, z2: 8192 } },
  "castle_courtyard": { "1": { img: "maps/castle_courtyard_1.webp", x1: -3583, x2: 3584, z1: -3830, z2: 1126 } },
  "castle_grounds": { "1": { img: "maps/castle_grounds_1.webp", x1: -8191, x2: 8192, z1: -8085, z2: 6813 } },
  "castle_inside": { "1": { img: "maps/castle_inside_1.webp", x1: -7431, x2: 4836, z1: -6242, z2: 3174 }, "2": { img: "maps/castle_inside_2.webp", x1: -7252, x2: 7455, z1: -3811, z2: 7641 }, "3": { img: "maps/castle_inside_3.webp", x1: -4146, x2: 11008, z1: -4351, z2: 3058 } },
  "ccm": { "1": { img: "maps/ccm_1.webp", x1: -8191, x2: 8192, z1: -8191, z2: 8192 }, "2": { img: "maps/ccm_2.webp", x1: -8191, x2: 8192, z1: -8191, z2: 8192 } },
  "cotmc": { "1": { img: "maps/cotmc_1.webp", x1: -4746, x2: 1362, z1: -7479, z2: 4301 } },
  "ddd": { "1": { img: "maps/ddd_1.webp", x1: -6655, x2: 9037, z1: -3583, z2: 3584 }, "2": { img: "maps/ddd_2.webp", x1: -6041, x2: 6989, z1: -7167, z2: 6659 } },
  "hmc": { "1": { img: "maps/hmc_1.webp", x1: -8089, x2: 7578, z1: -8191, z2: 8064 } },
  "jrb": { "1": { img: "maps/jrb_1.webp", x1: -7818, x2: 8276, z1: -7563, z2: 8058 }, "2": { img: "maps/jrb_2.webp", x1: -1311, x2: 1876, z1: -3358, z2: 3699 } },
  "lll": { "1": { img: "maps/lll_1.webp", x1: -8191, x2: 8192, z1: -8191, z2: 8192 }, "2": { img: "maps/lll_2.webp", x1: -2942, x2: 2943, z1: -2942, z2: 2943 } },
  "pss": { "1": { img: "maps/pss_1.webp", x1: -8191, x2: 8192, z1: -8191, z2: 8192 } },
  "rr": { "1": { img: "maps/rr_1.webp", x1: -8191, x2: 8192, z1: -8191, z2: 8192 } },
  "sa": { "1": { img: "maps/sa_1.webp", x1: -3276, x2: 3277, z1: -3276, z2: 3277 } },
  "sl": { "1": { img: "maps/sl_1.webp", x1: -8191, x2: 7168, z1: -8191, z2: 8192 }, "2": { img: "maps/sl_2.webp", x1: -2047, x2: 2048, z1: -2047, z2: 3482 } },
  "ssl": { "1": { img: "maps/ssl_1.webp", x1: -8447, x2: 8192, z1: -8191, z2: 8192 }, "2": { img: "maps/ssl_2.webp", x1: -3993, x2: 3994, z1: -4148, z2: 6758 } },
  "thi": { "1": { img: "maps/thi_1.webp", x1: -8191, x2: 8192, z1: -8191, z2: 8192 }, "2": { img: "maps/thi_2.webp", x1: -2457, x2: 2458, z1: -8191, z2: 2458 }, "3": { img: "maps/thi_3.webp", x1: -2047, x2: 2048, z1: -2047, z2: 2458 } },
  "totwc": { "1": { img: "maps/totwc_1.webp", x1: -8191, x2: 8192, z1: -8191, z2: 8192 } },
  "ttc": { "1": { img: "maps/ttc_1.webp", x1: -2080, x2: 3301, z1: -2489, z2: 3301 } },
  "ttm": { "1": { img: "maps/ttm_1.webp", x1: -8191, x2: 8192, z1: -8058, z2: 8325 }, "2": { img: "maps/ttm_2.webp", x1: -8191, x2: 8192, z1: -8191, z2: 8192 } },
  "vcutm": { "1": { img: "maps/vcutm_1.webp", x1: -6553, x2: 4915, z1: -6553, z2: 6554 } },
  "wdw": { "1": { img: "maps/wdw_1.webp", x1: -3839, x2: 4608, z1: -4351, z2: 4608 }, "2": { img: "maps/wdw_2.webp", x1: -3839, x2: 4569, z1: -3800, z2: 3840 } },
  "wf": { "1": { img: "maps/wf_1.webp", x1: -8191, x2: 8192, z1: -8191, z2: 8192 } },
  "wmotr": { "1": { img: "maps/wmotr_1.webp", x1: -8191, x2: 8192, z1: -8191, z2: 8192 } },
};
