"use strict";
// Generated by tools/build_maps.py -- do not edit by hand.
// Per-level top-down map backgrounds for the Map tab. Each entry is the
// world-space rectangle (x/z plane) its image covers: left=x1, right=x2,
// top=z1, bottom=z2 (north up, +z downward). Images derived from STROOP
// (MIT, (c) 2019 SM64 TAS & ABC) -- see maps/STROOP-LICENSE.txt.
window.SM64_MAPS = {
  "bbh": { img: "maps/bbh.webp", x1: -4197, x2: 5530, z1: -3993, z2: 6758 },
  "bitdw": { img: "maps/bitdw.webp", x1: -8191, x2: 8192, z1: -8191, z2: 8192 },
  "bitfs": { img: "maps/bitfs.webp", x1: -8191, x2: 8192, z1: -8191, z2: 8192 },
  "bits": { img: "maps/bits.webp", x1: -8191, x2: 8192, z1: -8191, z2: 8192 },
  "bob": { img: "maps/bob.webp", x1: -8191, x2: 8192, z1: -8191, z2: 8192 },
  "bowser_1": { img: "maps/bowser_1.webp", x1: -7167, x2: 7168, z1: -7167, z2: 7168 },
  "bowser_2": { img: "maps/bowser_2.webp", x1: -6545, x2: 6546, z1: -6545, z2: 6546 },
  "bowser_3": { img: "maps/bowser_3.webp", x1: -8191, x2: 8192, z1: -8191, z2: 8192 },
  "castle_courtyard": { img: "maps/castle_courtyard.webp", x1: -3583, x2: 3584, z1: -3830, z2: 1126 },
  "castle_grounds": { img: "maps/castle_grounds.webp", x1: -8191, x2: 8192, z1: -8085, z2: 6813 },
  "castle_inside": { img: "maps/castle_inside.webp", x1: -7431, x2: 4836, z1: -6242, z2: 3174 },
  "ccm": { img: "maps/ccm.webp", x1: -8191, x2: 8192, z1: -8191, z2: 8192 },
  "cotmc": { img: "maps/cotmc.webp", x1: -4746, x2: 1362, z1: -7479, z2: 4301 },
  "ddd": { img: "maps/ddd.webp", x1: -6655, x2: 9037, z1: -3583, z2: 3584 },
  "hmc": { img: "maps/hmc.webp", x1: -8089, x2: 7578, z1: -8191, z2: 8064 },
  "jrb": { img: "maps/jrb.webp", x1: -7818, x2: 8276, z1: -7563, z2: 8058 },
  "lll": { img: "maps/lll.webp", x1: -8191, x2: 8192, z1: -8191, z2: 8192 },
  "pss": { img: "maps/pss.webp", x1: -8191, x2: 8192, z1: -8191, z2: 8192 },
  "rr": { img: "maps/rr.webp", x1: -8191, x2: 8192, z1: -8191, z2: 8192 },
  "sa": { img: "maps/sa.webp", x1: -3276, x2: 3277, z1: -3276, z2: 3277 },
  "sl": { img: "maps/sl.webp", x1: -8191, x2: 7168, z1: -8191, z2: 8192 },
  "ssl": { img: "maps/ssl.webp", x1: -8447, x2: 8192, z1: -8191, z2: 8192 },
  "thi": { img: "maps/thi.webp", x1: -8191, x2: 8192, z1: -8191, z2: 8192 },
  "totwc": { img: "maps/totwc.webp", x1: -8191, x2: 8192, z1: -8191, z2: 8192 },
  "ttc": { img: "maps/ttc.webp", x1: -2080, x2: 3301, z1: -2489, z2: 3301 },
  "ttm": { img: "maps/ttm.webp", x1: -8191, x2: 8192, z1: -8058, z2: 8325 },
  "vcutm": { img: "maps/vcutm.webp", x1: -6553, x2: 4915, z1: -6553, z2: 6554 },
  "wdw": { img: "maps/wdw.webp", x1: -3839, x2: 4608, z1: -4351, z2: 4608 },
  "wf": { img: "maps/wf.webp", x1: -8191, x2: 8192, z1: -8191, z2: 8192 },
  "wmotr": { img: "maps/wmotr.webp", x1: -8191, x2: 8192, z1: -8191, z2: 8192 },
};
